pgsql:
  image: unocha/postgres93
  environment:
    DNSDOCK_NAME: pgsql
    DNSDOCK_IMAGE: hrinfo
  volumes:
    - /data/hrinfo/pgsql:/var/lib/pgsql/9.3/data
    - ./hrinfo_snapshot.sh:/tmp/hrinfo_snapshot.sh
web:
  build: .
  environment:
    DNSDOCK_NAME: www
    DNSDOCK_IMAGE: hrinfo
  volumes:
    - ./code:/var/www/html:rw
  links:
    - pgsql:pgsql
    - solr3:solr
    - mailhog:mailhog
solr3:
  image: unocha/solr3
  environment:
    DNSDOCK_NAME: solr
    DNSDOCK_IMAGE: hrinfo
mailhog:
  image: mailhog/mailhog
  ports:
    - 8025:8025
    - 1025:1025
