pgsql:
  image: unocha/postgres93
  environment:
    DNSDOCK_NAME: pgsql
    DNSDOCK_IMAGE: hrinfo
  volumes:
    - /data/hrinfo/pgsql:/var/lib/pgsql/9.3/data
  hostname: pgsql.hrinfo.vm
web:
  build: .
  environment:
    DNSDOCK_NAME: www
    DNSDOCK_IMAGE: hrinfo
  volumes:
    - ./code:/var/www/html
  links:
    - pgsql:pgsql
    - solr3:solr
  hostname: www.hrinfo.vm
solr3:
  image: unocha/solr3
  environment:
    DNSDOCK_NAME: solr
    DNSDOCK_IMAGE: hrinfo
